name: Generate Snake Game

on:
  # Schedule to run every 12 hours
  schedule:
    - cron: '0 */12 * * *'  # This runs at the top of every 12th hour

  # Also run on push to the main branch
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload Snake Game Artifacts
        uses: actions/upload-artifact@v3  # Updated to version 3
        with:
          name: snake-game-artifacts
          path: dist/
